package fixtures

import (
	"github.com/bilus/fencer/feature"
	"github.com/bilus/fencer/primitives"
	"strconv"
)

var Countries = []*Country{
	{1, "Vatican City", 800, -0.011, "Europe", makeRect(bounds[0])},
	{2, "Tokelau", 1300, 0.014, "Polynesia", makeRect(bounds[1])},
	{3, "Niue", 1600, -0.004, "Polynesia", makeRect(bounds[2])},
	{4, "Tuvalu", 11200, 0.009, "Oceania", makeRect(bounds[3])},
	{5, "Nauru", 11300, 0.001, "Oceania", makeRect(bounds[4])},
	{6, "Poland", 38224, -0.001, "Europe", makeRect(bounds[5])},
	{7, "Ukraine", 44400, 0, "Europe", makeRect(bounds[6])},
}

type CountryID int

func (id CountryID) String() string {
	return strconv.Itoa(int(id))
}

type Country struct {
	ID           CountryID
	Name         string
	Population   int
	Change       float64
	Region       string
	BoundingRect *primitives.Rect
}

var _ feature.Feature = (*Country)(nil)

func (c *Country) Key() feature.Key {
	return feature.Key(c.ID)
}

func (c *Country) Contains(p primitives.Point) (bool, error) {
	return p.MinDist(c.BoundingRect) == 0, nil
}

func (c *Country) Bounds() *primitives.Rect {
	return c.BoundingRect
}

// Really, really rough boundaries generated by  following steps in: https://github.com/JamesChevalier/cities, importing into geojson.io and drawing bounding boxes around the polygons.

var bounds = [][]primitives.Point{
	// Vatican City
	{
		{12.44450569152832, 41.89978557507729},
		{12.459547519683836, 41.89978557507729},
		{12.459547519683836, 41.907946360630994},
		{12.44450569152832, 41.907946360630994},
	},
	// Tokelau
	{
		{-172.7874755859375, -9.66573839518868},
		{-170.947265625, -9.66573839518868},
		{-170.947265625, -8.303905908124174},
		{-172.7874755859375, -8.303905908124174},
	},
	// Niue
	{
		{-170.13702392578125, -19.265776189877485},
		{-169.5849609375, -19.265776189877485},
		{-169.5849609375, -18.818567424622376},
		{-170.13702392578125, -18.818567424622376},
	},
	// Tuvalu
	{
		{174.74853515625, -11.059820828563412},
		{180.296630859375, -11.059820828563412},
		{180.296630859375, -5.397273407690904},
		{174.74853515625, -5.397273407690904},
	},
	// Nauru
	{
		{166.79443359375, -0.6227752122036241},
		{167.07595825195312, -0.6227752122036241},
		{167.07595825195312, -0.4051174740026618},
		{166.79443359375, -0.4051174740026618},
	},
	// Poland
	{
		{14.04052734375, 48.922499263758255},
		{24.27978515625, 48.922499263758255},
		{24.27978515625, 54.99022172004893},
		{14.04052734375, 54.99022172004893},
	},
	// Ukraine
	{
		{21.665039062499996, 44.02442151965934},
		{40.341796875, 44.02442151965934},
		{40.341796875, 52.482780222078226},
		{21.665039062499996, 52.482780222078226},
	},
}
